### ISSUE TITLE
tagbar is empty

### ISSUE THREAD

**Issue by lauccode** [andreyorst/tagbar.kak#13]
## Problem description
It is a long time I don't use it.

## Steps to reproduce
But I installed universal-ctags on last ubuntu release.
Kakoune on Ubuntu with package manager (strange, kak -version say Kakoune unknown)
I added the config for tagbar as adviced on github. And I did "plug-install"
ctags-generate command has been done. I can see the tags file in directory.
When I open a .cpp, the tagbar is open but is empty 

Here is my kakrc used :
https://github.com/lauccode/config/blob/master/kakrc

**Comment by andreyorst** [comment]
tagbar should automatically generate ctags information for the current file, so perhaps there's some problem with that.

I've installed the `ctags` package from my distro repository and tagbar shows tags for a sample cpp file with your `kakrc`. 

What does `ctags --version` say?

**Comment by lauccode** [comment]
It's say :
Universal Ctags 5.9.0, Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep  3 2021, 18:12:18
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc, +optscript

**Comment by andreyorst** [comment]
> Don't you need readtags also ? 

I believe it comes with universal-ctags.

Are there any errors in the `*debug*` buffer?

**Comment by lauccode** [comment]
Yes, I can see readtags is available too.
debug buffer just after start of tmux and kak on a .cpp :

**·This·is·the·debug·buffer,·where·debug·info·will·be·written·***¬                                       │¬  
powerline.kak:·Warning,·trying·to·load·non-existing·module·'git'¬                                         │~  
powerline.kak:·Warning,·trying·to·load·non-existing·module·'bufname'¬                                     
powerline.kak:·Warning,·trying·to·load·non-existing·module·'line_column'¬                                 
powerline.kak:·Warning,·trying·to·load·non-existing·module·'mode_info'¬                                   
powerline.kak:·Warning,·trying·to·load·non-existing·module·'filetype'¬                                    │~         
powerline.kak:·Warning,·trying·to·load·non-existing·module·'client'¬                                      │~        
powerline.kak:·Warning,·trying·to·load·non-existing·module·'session'¬                                     │~                           
powerline.kak:·Warning,·trying·to·load·non-existing·module·'position'¬                                    │~                           
kak-lsp:·config-change·detected:·¬                                                                        │~                           
remote·client·connected:·5¬                                                                               │~                           
kak-lsp:·config-change·detected:·¬                                                                        │~                           
kak-lsp:·language·server·is·not·initialized,·parking·request

**Comment by andreyorst** [comment]
Strange, so there are no tagbar related errors, yet it's still empty.

Can you delete the `rm -rf ${tmp}` part in the [line 221](https://github.com/andreyorst/tagbar.kak/blob/a664443f8bf4e99f6edc0f10527d2384815ae994/rc/tagbar.kak#L221) and check what ends up int the generated tmp file?

**Comment by lauccode** [comment]
I removed the line.
I updated the plugin.
I launch .cpp with kak after tmux and see the tagbar. 
I close kak.
But I don't see new ~/tmp after that.

**Comment by lauccode** [comment]
In /tmp there is new file : preamble-c528da.pch 
after to launch kak with tagbar open on cpp file.

**Comment by andreyorst** [comment]
> I removed the line.

You should not remove the whole line, just the `rm` call

> I updated the plugin.

This could get rid of all your modifications, no need to update it.

> I launch .cpp with kak after tmux and see the tagbar. I close kak.

No need to close kak, there's a hook that deletes all tabar-related files in a close hook.

**Comment by lauccode** [comment]
Yes, I just remove rm call, not the whole line.
OK, I will not update.
and no need to close kak.
I retried but I can not see tagbar information in /tmp/ and no creation of ~/tmp

**Comment by andreyorst** [comment]
I've noticed that I'm using a quite old build of kakoune, so I've updated it, and now tagbar is also empty for me. Will look into this.

**Comment by andreyorst** [comment]
Unfortunately, I don't know what's wrong. All I can suggest to you now is to debug this function:

https://github.com/andreyorst/tagbar.kak/blob/a664443f8bf4e99f6edc0f10527d2384815ae994/rc/tagbar.kak#L158-L223

Try adding some `printf` calls into it, which would echo to the `*debug*` buffer. I suspect that something is not correct in your system.

Additionally, if you have a minimal `.cpp` project I could try this on, could you upload it here as an archive?

**Comment by lauccode** [comment]
For minimal .cpp I'm using :
https://github.com/memsharded/hello

**Comment by andreyorst** [comment]
Works on my end:

![image](https://user-images.githubusercontent.com/19470159/195983506-056382ea-a48b-4364-ab4f-34a73817fd63.png)

I'm out of ideas.

**Comment by lauccode** [comment]
Hello Andre, 
I install last kakoune(v2021.11.07) with the UBUNTU software and it is working now.
Thanks a lot for your help.

**Comment by andreyorst** [comment]
I'm glad it works!
