### ISSUE TITLE
OSX Compatibility issue with awk

### ISSUE THREAD

**Issue by nikhilmitrax** [andreyorst/tagbar.kak#3]
It seems that tagbar is not compatible with OSX's version of `awk`.

Using `gawk` in `tagbar.kak` instead of `awk` fixes this issue.

Would it be possible to test for `gawk` in the beginning and then use `gawk` or `awk` depending on which one is available?

**Comment by andreyorst** [comment]
It would be better if the script will work with the `awk` presented in MacOS. What are the exact errors?

**Comment by nikhilmitrax** [comment]
```awk: illegal primary in regular expression ? at 
 source line number 3
 context is
	                gsub("&", "&&", keys); gsub("?", "??", >>>  keys) <<< 
>>>

```

**Comment by andreyorst** [comment]
weird. This code works with `busybox awk`, I've assumed that it would work with any other awk. I need to set up BSD machine to test this. This would take some time.

**Comment by andreyorst** [comment]
should work now. Can you please test it?

**Comment by nikhilmitrax** [comment]
I tested it on a fresh macbook pro runnning native `awk` and it seems to work!

Thanks!
