### ISSUE TITLE
Expose ctags command in option

### ISSUE THREAD

**Issue by SolitudeSF** [andreyorst/tagbar.kak#4]
For providing custom ctags executable depending on filetype.

**Comment by andreyorst** [comment]
Hm. How would this work? The `ctags` output is being parsed by `awk`, so if you change `ctags` to something else, like `gnu-global` it will not be able to parse. What's on your mind?

Also, there are currently 102 different hooks for various filetypes to provide support. Isn't this enough?

**Comment by SolitudeSF** [comment]
it should be a ctags compatible implementation. well, there are more than 102 languages, and i dont see one that i need.

**Comment by andreyorst** [comment]
I'm not against the feature, but I'm curious which one do you need.

I'll add the option this evening.

**Comment by SolitudeSF** [comment]
there is ctags implementation for nim https://bitbucket.org/nimcontrib/ntags. its limited but should work. it doesnt have sort flag, but i could botch something in.

**Comment by andreyorst** [comment]
`ntags` isn't available in my distro, so I can't test it rightnow, but there's now a branch for testing the feature. I'm interested in your feedback.

**Comment by SolitudeSF** [comment]
uhhh, i've set tagbar_ctags_cmd, but it throws "Filetype 'nim' is not supported by Tagbar" on `tagbar-enable`. is there some additional configuration i should do?

**Comment by andreyorst** [comment]
Ah, I've forgot about this. Sorry, you need to manually set `tagbar_kinds` option to `'nim' 'ntags kinds'` so tagbar could parse output.

**Comment by andreyorst** [comment]
I think we can add this to tagbar.kak when it will work fine, so only thing would be needed for end user is installation of `ntags`

**Comment by SolitudeSF** [comment]
it works 
![image](https://user-images.githubusercontent.com/10168645/54686209-6b6fbe00-4b21-11e9-8bc2-f23387eebd60.png)

```
set buffer tagbar_ctags_cmd 'ntags'
set buffer tagbar_kinds 'f' 'Functions' 't' 'Types' 'v' 'Variables'
```

**Comment by andreyorst** [comment]
does `ntags` supports sorting?

**Comment by SolitudeSF** [comment]
looking at results i think that it implicitly sorts. it doesnt support disabling it.

**Comment by andreyorst** [comment]
Hm. Ok.

I suppose that we can add this to tagbar.kak

    hook global WinSetOption filetype=nim %sh{
        if [ -n "$(command -v ntags)" ]; then
            printf "%s\n" "set window tagbar_ctags_cmd 'ntags'
                           set window tagbar_kinds 'f' 'Functions' 't' 'Types' 'v' 'Variables'"
        fi
    }

**Comment by SolitudeSF** [comment]
if configurable sorting is requirement, i could someday soon, if i get to it, add working cli switch and then submit a pr to you with this config. otherwise i dont think that out of <5 kakoune+nim users someone will get bitten by unexpected sorting behavior.

**Comment by andreyorst** [comment]
It's not required. I'm just thinking about proper custom `ctags` commands handling. Currently, I check if `tagbar_ctags_cmd` is etither set to `ctags` or anything else, and sorting is explicitly handled by  user configuration only for `ctags`:

    case ${kak_opt_tagbar_ctags_cmd} in
        ctags)
            ctags="ctags --sort='${kak_opt_tagbar_sort:-yes}' -f '$tags' '$kak_buffile'" ;;
        ctags*|*)
            ctags="${kak_opt_tagbar_ctags_cmd} -f '$tags' '$kak_buffile'" ;;
    esac

if some implementation of `ctags` supports some kind of sorting, current implementation requires it to be passed inside `tagbar_ctags_cmd`, like `ntags --sort-tags true`

**Comment by andreyorst** [comment]
I've added nim support to feature branch

**Comment by SolitudeSF** [comment]
small question. is ctags spec dictates what tag kinds can be specifier or are these just arbitrary one letter identifiers mapped to arbitrary headers (`tagbar_kinds`).

**Comment by andreyorst** [comment]
didn't read ctags specs, but for all supported languages all `kinds` are one letter identifiers.

**Comment by SolitudeSF** [comment]
i mean, if i would rename `Functions` to `Procedures`, since thats the correct name for them in nim would that go against some ctags guidelines?

**Comment by andreyorst** [comment]
No, this is tagbar only names.

**Comment by andreyorst** [comment]
nim lang supprot is now available in master branch, you don't need to define kinds or change ctags implementation for it.

**Comment by SolitudeSF** [comment]
thanks!
